/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9fb",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f6",
        "surface-container": "#edeef0",
        "surface-container-high": "#e7e8ea",
        "surface-container-highest": "#e1e2e4",
        "on-surface": "#191c1e",
        "on-surface-variant": "#434654",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f3",
        outline: "#737685",
        "outline-variant": "#c3c6d6",
        "surface-tint": "#0c56d0",
        primary: "#003d9b",
        "on-primary": "#ffffff",
        "primary-container": "#0052cc",
        "on-primary-container": "#c4d2ff",
        "inverse-primary": "#b2c5ff",
        secondary: "#00687a",
        "on-secondary": "#ffffff",
        "secondary-container": "#6ae1ff",
        "on-secondary-container": "#006374",
        tertiary: "#3c444f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#535c67",
        "on-tertiary-container": "#cbd4e1",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dae2ff",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed": "#001848",
        "on-primary-fixed-variant": "#0040a2",
        "secondary-fixed": "#adecff",
        "secondary-fixed-dim": "#5dd6f3",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5d",
        "tertiary-fixed": "#dae3f0",
        "tertiary-fixed-dim": "#bec7d4",
        "on-tertiary-fixed": "#131c25",
        "on-tertiary-fixed-variant": "#3f4852",
        background: "#f8f9fb",
        "on-background": "#191c1e",
        "surface-variant": "#e1e2e4",
        /* Semantic status tones (desaturated per spec) */
        "status-high-bg": "#dcf5df",
        "status-high-text": "#146c2e",
        "status-moderate-bg": "#ffefc2",
        "status-moderate-text": "#8a6100",
        "status-low-bg": "#e7e8ea",
        "status-low-text": "#434654",
      },
      fontFamily: {
        display: ["Outfit", "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        level2: "0px 4px 20px rgba(0, 0, 0, 0.04)",
        level3: "0px 20px 40px rgba(0, 82, 204, 0.08)",
      },
      maxWidth: {
        app: "1200px",
      },
      spacing: {
        gutter: "24px",
      },
    },
  },
  plugins: [],
};
